[package]
name = "grrs"
version = "0.1.0"
authors = ["Brandon <brandon@qwang.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[test]]
name = "integration"
path = "tests/utests.rs"


[dependencies]
structopt = "0.2.10"
